// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _TOcaf_Application_HeaderFile
#define _TOcaf_Application_HeaderFile

#include <TDocStd_Application.hxx>
#include <Standard_CString.hxx>
#include <TDocStd_Document.hxx>
#include <TColStd_SequenceOfExtendedString.hxx>

//class TColStd_SequenceOfExtendedString;
//class TDocStd_Document;


class TOcaf_Application : public TDocStd_Application {

public:

 // Methods PUBLIC
 // 
Standard_EXPORT TOcaf_Application();
Standard_EXPORT virtual  void Formats(TColStd_SequenceOfExtendedString& Formats) ;
Standard_EXPORT   Standard_CString ResourcesName() ;

// OCCT RTTI
DEFINE_STANDARD_RTTIEXT(TOcaf_Application, TDocStd_Application)

#if 0
 // Type management
 Standard_EXPORT friend Handle_Standard_Type& TOcaf_Application_Type_();
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;
#endif

};

// other inline functions and methods (like "C++: function call" methods)
//

#endif
